2016-02-16 22:04:43,787 : INFO : Machine : Mission Pinball Framework v0.30.0.dev433
2016-02-16 22:04:43,818 : INFO : Machine : Loading config from original files
2016-02-16 22:04:43,896 : INFO : Machine : Machine config file #1: Z:\git\mpf-examples\demo_man\config\config
2016-02-16 22:04:44,240 : INFO : Machine : Config file cache created: Z:\git\mpf-examples\demo_man\__mpfcache__\config_config.p
2016-02-16 22:04:44,240 : INFO : Machine : Loading core modules...
2016-02-16 22:04:44,428 : INFO : DeviceManager : Loading devices...
2016-02-16 22:04:44,506 : ERROR : ConfigProcessor : Your config contains a value for the setting "show_player:tocks_per_sec", but this is not a valid setting name.
2016-02-16 22:04:44,537 : ERROR : root : Your config contains a value for the setting "show_player:tocks_per_sec", but this is not a valid setting name.
Traceback (most recent call last):
  File "c:\python34\lib\site-packages\mpf\commands\core.py", line 133, in __init__
    MachineController(mpf_path, machine_path, vars(args)).run()
  File "c:\python34\lib\site-packages\mpf\core\machine.py", line 139, in __init__
    self.events.process_event_queue()
  File "c:\python34\lib\site-packages\mpf\core\events.py", line 492, in process_event_queue
    **event[3])
  File "c:\python34\lib\site-packages\mpf\core\events.py", line 430, in _process_event
    result = handler[0](**merged_kwargs)
  File "c:\python34\lib\site-packages\mpf\core\mode_controller.py", line 84, in _load_modes
    self.machine.modes[mode] = self._load_mode(mode.lower())
  File "c:\python34\lib\site-packages\mpf\core\mode_controller.py", line 185, in _load_mode
    self.machine, config, mode_string, mode_path)
  File "c:\python34\lib\site-packages\mpf\modes\attract\code\attract.py", line 16, in __init__
    super().__init__(machine, config, name, path)
  File "c:\python34\lib\site-packages\mpf\core\mode.py", line 74, in __init__
    **item.kwargs)
  File "c:\python34\lib\site-packages\mpf\core\config_player.py", line 59, in process_config
    self.config_file_section, these_settings)
  File "c:\python34\lib\site-packages\mpf\core\config_validator.py", line 969, in validate_config
    validation_failure_info)
  File "c:\python34\lib\site-packages\mpf\core\config_validator.py", line 1131, in check_for_invalid_sections
    'setting "' + path_string + '", but this is not a valid '
AssertionError: Your config contains a value for the setting "show_player:tocks_per_sec", but this is not a valid setting name.
